### ISSUE TITLE
Unable to deploy on Lambda

### ISSUE THREAD

**Issue by Tilotiti** [beneboy/lambda-browser-screenshots#2]
Hello,

When I try to deploy on Lambda, I'm having this error :

`/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory` 

After reading some stackoverflow, I tried to upgrade the Chromius/Puppeter to version 6, but it then reached the max limit of the 50Mb for the zip.

Have you got any workaround ?

**Comment by beneboy** [comment]
Hi, I think this issue is with Node 16 on Lambda. If you deploy the latest code to a Node 14 Lambda it should work.

**Comment by Tilotiti** [comment]
Exactly. Thank you :)
